### PR TITLE
Feature: Callout Mode

### PR DESCRIPTION
**Pull request by JCGithu**
Adding a setting that includes the users review and film poster in a custom [!letterboxd] callout. This setting is off by default. Example image below.

Benefits of using custom callout:
- Easier for users to customise styles.
- Easier to embed blocks, for example in daily notes.
- Easier searching in dataview

Callouts can be minimised but default to being open. Could potentially have an additional option for this but that feels too detailed imo. If there is no review text it remains as a header. 

Custom CSS is used for:
- Letterboxd colour scheme.
- Film poster styling. (Text wrapping, placement, matching Letterboxd homepage, etc.) 
- Making callout icon the Letterboxd icon.

Obsidian_rzGqwZ3qEa

### CODE REVIEW

**Comment by Fleker** [comment]
I like the concept. Do you think this could lead to performance issues if the user has too many of these callouts?

In terms of settings, should we use a toggle here or perhaps a "Display" dropdown with multiple options for "Text-Only" and "Callouts"?

**Comment by JCGithu** [comment]
I've looked into it a bit and I can't seem to find any people mentioning performance issues when it comes to callouts. At the end of the day this is all being rendered in Electron so I imagine it's no more stressful than a regular site. 

I've taken your advice and made a few changes:
- Made the callout setting 'Display' with four options: Text, Text w/ Review, Callout, Callout w/ Poster. Let me know if this is too granular! 
- Added a 'Star' setting. Thought about putting this in another PR, but it does tie in with 'Display' setting.
- Changed output to be a switch function with comments to make the differing options clearer.

**Comment by Fleker** [comment]
Yes this looks a lot better, just a few comments

**Comment by JCGithu** [comment]
Sorry do you mean you have a few comments _about_ the code, or that there are too many comments _actually in the code_? Thanks!

**Comment by Fleker** [comment]
I had added a few comments as part of my review. There are four of them. Hopefully they aren't too complicated.

**Comment by JCGithu** [comment]
Hey, I can't seem to see any review comments anywhere — are you sure they were submitted? I can see your requested changes on the other open PR with no issue. Thanks

**Review by Fleker — COMMENTED** [review]
Whoops sorry I forgot to "Finish my review"

**Comment by JCGithu** [comment]
Made those changes! 

- Broke out the section you suggested into printOut. As a lot of variables were defined within that map function I ended up breaking out more than expected.
- Used literal strings instead of enum for callout setting.
- Removed unused 'SetIcon' dependancy
- Added a default case to starParser & marked rating nullable
- Removed that CSS comment

**Comment by Fleker** [comment]
Looks good to me. I'll package this up now.

**Pull request merged**
